on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo check
        run: cargo check --locked
      - name: Cargo format check
        run: cargo fmt --check
      - name: Cargo build
        run: cargo build --locked
      - name: Cargo test
        run: cargo test --locked
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
